version: '3.8'

services:
  authentication_service:
    build: ./Authentication_Service
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db 
    networks:
      - app_network

  analytics_service:
    build: ./Analytics_Service
    ports:
      - "5001:5001"
    depends_on:
      - mysql_db
    networks:
      - app_network

  webapp_enter:
    build: ./WebApp_Enter
    ports:
      - "5002:5002"
    depends_on:
      - authentication_service
      - mysql_db
    networks:
      - app_network

  webapp_results:
    build: ./WebApp_Results
    ports:
      - "5003:5003"
    depends_on:
      - analytics_service
      - mongo_db
    networks:
      - app_network

  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file: 
      - .env
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "ahmad_qasem"
      MONGO_INITDB_ROOT_PASSWORD: "ahmad@2003"
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: